### PR TITLE
Terms of use: drop limitation on 500 installations per year

### PR DESCRIPTION
**Pull request by dsd**
https://phabricator.endlessm.com/T33418

### CODE REVIEW

**Comment by wjt** [comment]
I guess you will need to enlist a Portuguese speaker to update that one?

**Comment by dsd** [comment]
The Portuguese terms are far out of date anyway (https://phabricator.endlessm.com/T31876)

**Comment by wjt** [comment]
I tried to diff these with diffoscope and even with my nonexistent Spanish I can see that the PDF change is correct in both and the English change is also correct in the docx.

What's a bit weird is that diffoscope refused to give a rich diff of the two versions of the Spanish file and instead gave a massive binary diff. I think it's because its format is now being sniffed as something different. `old` is a worktree of the current master commit:

```
wjt@camille:~/src/endlessm/eos-license-service (T33418)$ file --mime-type ./old/terms/eos/es/Terms-of-Use.docx ./terms/eos/es/Terms-of-Use.docx
./old/terms/eos/es/Terms-of-Use.docx: application/vnd.openxmlformats-officedocument.wordprocessingml.document
./terms/eos/es/Terms-of-Use.docx:     application/octet-stream
```

Diffing the content inside the `docx` does show some weird stuff:

```
│ │ -        <w:t xml:space="preserve">Lo invitamos a descargar e instalar el Software para su uso personal o en un modo no comercial como una institución pública, educativa o no lucrativa. Se le permite instalar el Software en 500 equipos de cómputo por año para las opciones descritas. Estas instalaciones deben ser hechas con los métodos de instalación descritos en nuestra documentación; excepto en los casos descritos en estos Términos, las modificaciones al Software no estan permitidas.</w:t>
│ │ +        <w:t xml:space="preserve">Lo invitamos a descargar e instalar el Software para su uso personal o en un modo no comercial como una institución pública, educativa o no lucrativa. Se le permite instalar el Software en 1 o m</w:t>
│ │ +      </w:r>
│ │ +      <w:r>
│ │ +        <w:rPr>
│ │ +          <w:rFonts w:eastAsia="Times New Roman" w:cs="Arial"/>
│ │ +          <w:color w:val="auto"/>
│ │ +          <w:kern w:val="2"/>
│ │ +          <w:sz w:val="20"/>
│ │ +          <w:szCs w:val="20"/>
│ │ +          <w:lang w:val="es-MX" w:eastAsia="zh-CN" w:bidi="hi-IN"/>
│ │ +        </w:rPr>
│ │ +        <w:t>ás</w:t>
│ │ +      </w:r>
│ │ +      <w:r>
│ │ +        <w:rPr>
│ │ +          <w:rFonts w:cs="Arial"/>
│ │ +          <w:sz w:val="20"/>
│ │ +          <w:szCs w:val="20"/>
│ │ +        </w:rPr>
│ │ +        <w:t xml:space="preserve">equipos de cómputo para las opciones descritas. Estas instalaciones deben ser hechas con los métodos de instalación descritos en nuestra documentación; excepto en los casos descritos en estos Términos, las modificaciones al Software no est</w:t>
│ │ +      </w:r>
│ │ +      <w:r>
│ │ +        <w:rPr>
│ │ +          <w:rFonts w:eastAsia="Times New Roman" w:cs="Arial"/>
│ │ +          <w:color w:val="auto"/>
│ │ +          <w:kern w:val="2"/>
│ │ +          <w:sz w:val="20"/>
│ │ +          <w:szCs w:val="20"/>
│ │ +          <w:lang w:val="es-MX" w:eastAsia="zh-CN" w:bidi="hi-IN"/>
│ │ +        </w:rPr>
│ │ +        <w:t>á</w:t>
│ │ +      </w:r>
│ │ +      <w:r>
│ │ +        <w:rPr>
│ │ +          <w:rFonts w:cs="Arial"/>
│ │ +          <w:sz w:val="20"/>
│ │ +          <w:szCs w:val="20"/>
│ │ +        </w:rPr>
│ │ +        <w:t>n permitidas.</w:t>
```

**Review by wjt — APPROVED** [review]
Anyway, I'm not sure the bits above really matter. Just strange.

**Pull request merged**
